name: Trigger auto deployment for ca-medgps-api-kevkibe-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-medgps-api-kevkibe-dev-AutoDeployTrigger-626d9cac-5006-4bfc-92c2-de3e9004dc2c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAMEDGPSAPIKEVKIBEDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAMEDGPSAPIKEVKIBEDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAMEDGPSAPIKEVKIBEDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CAMEDGPSAPIKEVKIBEDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAMEDGPSAPIKEVKIBEDEV_REGISTRY_PASSWORD }}
          containerAppName: ca-medgps-api-kevkibe-dev
          resourceGroup: rg-MedGPS-API-Dev
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


